# Generated by Django 5.2.17 on 2026-09-08 15:39

import caricue.live.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('public_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('identity_mode', models.CharField(choices=[('display_name', 'Student types a display name'), ('roster_identifier', 'Student enters their roster identifier')], default='display_name', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='activities.activity')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='classroom.classroom')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, help_text='Self-entered label, or the roster identifier that was used.', max_length=80)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('participant_token', models.CharField(default=caricue.live.models.generate_public_token, editable=False, max_length=64, unique=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.livesession')),
                ('student', models.ForeignKey(blank=True, help_text='Set when the session identifies students against the roster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='classroom.student')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_response', models.TextField(blank=True, max_length=1000)),
                ('confidence_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_correct', models.BooleanField(blank=True, help_text='Null when the question is not deterministically scorable.', null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='live.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='activities.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='activities.choice')),
            ],
            options={
                'ordering': ['question__position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_gap', models.CharField(help_text='The main learning gap this check surfaced.', max_length=250)),
                ('plan_impact', models.CharField(choices=[('confirmed', 'Confirmed my lesson plan'), ('changed', 'Changed my lesson plan'), ('unclear', 'Still unclear / need more evidence')], default='confirmed', max_length=16)),
                ('planned_action', models.TextField(help_text='What the teacher will review, reteach or reinforce.', max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('live_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='live.livesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['classroom', 'status'], name='live_livese_classro_737453_idx'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status', 'closed')), models.Q(('closed_at__isnull', True), ('status', 'open')), _connector='OR'), name='live_session_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('live_session', 'student'), name='uniq_participant_student_per_session'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(models.F('live_session'), django.db.models.functions.text.Lower('display_name'), condition=models.Q(('student__isnull', True), models.Q(('display_name', ''), _negated=True)), name='uniq_participant_display_name_per_session'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question', 'is_correct'], name='live_respon_questio_fc6d4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='uniq_response_per_participant_question'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_value__isnull', True), models.Q(('confidence_value__gte', 1), ('confidence_value__lte', 5)), _connector='OR'), name='response_confidence_within_scale'),
        ),
    ]
