# Generated by Django 5.2.17 on 2026-09-08 15:39

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(blank=True, help_text='Grade, form or year level.', max_length=60)),
                ('academic_period', models.CharField(blank=True, help_text='Term or semester label, e.g. "2026 Term 1".', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('school_identifier', models.CharField(blank=True, help_text='Optional school/roll identifier used for roster-coded joins.', max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.student')),
            ],
            options={
                'ordering': ['student__display_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(models.F('teacher'), django.db.models.functions.text.Lower('name'), name='uniq_classroom_name_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(models.F('teacher'), django.db.models.functions.text.Lower('school_identifier'), condition=models.Q(('school_identifier', ''), _negated=True), name='uniq_student_school_identifier_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('classroom', 'student'), name='uniq_enrollment_per_classroom_student'),
        ),
    ]
